baseurl = "https://dev.pippi.im/"
languageCode = "en-us"
title = "/dev/ by Massimiliano Pippi"
pygmentsstyle = "manni"
mainSections = ["writing"]

[params.author]
name = "Massimiliano Pippi"
image = "img/massi.jpeg"
headline = "Software developer, engineering manager, I can ops."
bio = "A little bit about me"
links = [
    { github = "https://github.com/masci" },
    { bluesky = "https://bsky.app/profile/massi.pippi.im" },
    { linkedin = "http://www.linkedin.com/in/masci"}
]

# Syntax highlight
[markup]
  [markup.highlight]
    style = 'catppuccin-macchiato'
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        title = true
