[[main]]
name = "Now"
pageRef = "now"
weight = 10

[[main]]
name = "Stuff I write"
pageRef = "writing"
weight = 20

[[main]]
name = "Stuff I read"
pageRef = "book"
weight = 30

[[main]]
name = "Stuff I say"
pageRef = "talk"
weight = 40

[[main]]
name = "cv"
pageRef = "resume"
weight = 50

[[main]]
name = "GitHub"
url = "https://github.com/masci/dev"
weight = 100
[main.params]
icon = "github"
showName = false
target = "_blank"

[[main]]
name = "Bluesky"
url = "https://bsky.app/profile/massi.pippi.im"
weight = 110
[main.params]
icon = "bluesky"
showName = false
target = "_blank"
